### ISSUE TITLE
组件库文档无法跑起来

### ISSUE THREAD

**Issue by loca-spirit** [wocwin/t-ui-plus#1]
兄弟，这个好像文档无法渲染组件了。build也报错。usePageHead() is called without provider.

能帮忙调试出一个可用版本，让我学习下吗

**Comment by wocwin** [comment]
你的依赖有没有安装成功，我这边下载项目然后安装依赖是可以打开的
![image](https://user-images.githubusercontent.com/37534478/194685957-889a7cb1-3ea0-4ebd-a31d-02b51b7b87fa.png)

**Comment by wocwin** [comment]
> 兄弟，这个好像文档无法渲染组件了。build也报错。usePageHead() is called without provider.
> 
> 能帮忙调试出一个可用版本，让我学习下吗

文档拉取最新代码可打开；若需要看组件代码demo示例可看此项目 https://github.com/wocwin/wocwin-admin
