### ISSUE TITLE
组件使用出错，不显示

### ISSUE THREAD

**Issue by Crane821** [wocwin/t-ui-plus#10]
按照文档说明引入组件 
![image](https://github.com/wocwin/t-ui-plus/assets/137034596/caffafa8-3136-4ccb-9ceb-1791fbc7e501)
![image](https://github.com/wocwin/t-ui-plus/assets/137034596/89ee2c89-350c-4d16-b95d-fea3f6714f80)
![image](https://github.com/wocwin/t-ui-plus/assets/137034596/162f0aad-df6f-4c4d-b085-5649bbcec494)
![image](https://github.com/wocwin/t-ui-plus/assets/137034596/43799c88-f6ae-4943-ab8c-22a3428abaf1)

页面上空白无法显示组件，控制台提示如下信息
![image](https://github.com/wocwin/t-ui-plus/assets/137034596/7a37c000-049e-42d4-95f5-52df86259240)
![image](https://github.com/wocwin/t-ui-plus/assets/137034596/fb604f25-e6a8-40b9-86d7-56a0903bc8fa)
![image](https://github.com/wocwin/t-ui-plus/assets/137034596/5b228859-4bfb-4f45-9253-a01672079612)
试了其他组件也是一样的情况
![image](https://github.com/wocwin/t-ui-plus/assets/137034596/74b4a0af-dffa-4715-b51b-d893944f8bd7)

这个问题有解决方法没？
也是Vue3 + TS + ElementPlus的项目，以下是项目中其他依赖的信息。
![image](https://github.com/wocwin/t-ui-plus/assets/137034596/f0880dce-80f3-4add-b420-6640bd77a0c6)

![image](https://github.com/wocwin/t-ui-plus/assets/137034596/b9e93ef0-9d18-4d2c-9ba6-21d6678b825e)
![image](https://github.com/wocwin/t-ui-plus/assets/137034596/52adb1e4-8caa-4172-a409-364a2295d73e)

**Comment by wocwin** [comment]
使用T-ui-plus基础组件的前提是，优先全局安装**注册**element-plus组件库（不能使用按需加载插件注册）

**Comment by Crane821** [comment]
element-plus 是用unplugin-vue-components 插件引入的 。。
这个有办法解决吗，

**Comment by Crane821** [comment]
> 使用T-ui-plus基础组件的前提是，优先全局安装**注册**element-plus组件库（不能使用按需加载插件注册）

element-plus 是使用unplugin-vue-components插件引入的。是因为这个原因吗？

**Comment by wocwin** [comment]
> > 使用T-ui-plus基础组件的前提是，优先全局安装**注册**element-plus组件库（不能使用按需加载插件注册）
> 
> element-plus 是使用unplugin-vue-components插件引入的。是因为这个原因吗？

对就是这个原因
