### ISSUE TITLE
return (             <el-switch 会报错，是要做什么配置才可以吗

### ISSUE THREAD

**Issue by ming2882** [wocwin/t-ui-plus#12]
{
        prop: 'enableStatusLabel',
        label: '状态',
        minWidth: '80',
        render: (text, record) => {
          return (
            <el-switch
              active-value={1}
              inactive-value={2}
              v-model={record.enableStatus}
              onChange={() => handleStatusChange(record)}
            >
              {text}
            </el-switch>
          )
        },
      },

**Comment by wocwin** [comment]
把错误信息发出来，或者进微信交流群问问，如果是使用render 那么script中lang是tsx模式

**Comment by ming2882** [comment]
用的是<script lang="ts" setup>，要改ts改为tsx是吧

**Comment by wocwin** [comment]
> 用的是<script lang="ts" setup>，要改ts改为tsx是吧

对
