### ISSUE TITLE
怎么下载到本地测试有问题

### ISSUE THREAD

**Issue by zyptfy** [wocwin/t-ui-plus#16]
Cannot read properties of undefined (reading 'bind')
    at index.vue:649:39

**Comment by zyptfy** [comment]
![RK BUWJ((I9WH IXC{G5B0M](https://github.com/wocwin/t-ui-plus/assets/9477233/b9f99598-470b-4fa6-8c84-cab926f93e1e)

**Comment by zyptfy** [comment]
![RK BUWJ((I9WH IXC{G5B0M](https://github.com/wocwin/t-ui-plus/assets/9477233/2a1edf4b-3003-47d4-a861-c0423da3de6e)

**Comment by wocwin** [comment]
已经解决，需要晚上更新github代码，你本地需要改一下TTable源码（具体改动如图）
![image](https://github.com/wocwin/t-ui-plus/assets/37534478/d9c3ce6a-b68e-49fe-86a6-984450982e97)
