### ISSUE TITLE
获取Select Options 不合理

### ISSUE THREAD

**Issue by zsasjy** [wocwin/t-ui-plus#21]
这样获取options不是很合理，业务场景通常只会返回options结构的数据，而这个数据有可能多处用到而单独保存，建议params支持options，类型为Array<{label: string, value: number | string}>
![image](https://github.com/wocwin/t-ui-plus/assets/42797083/04417844-0440-46c3-9d2c-c69e16df8b2a)

**Comment by wocwin** [comment]
你加上isSelfCom:true,就可以不需要设置listTypeInfo[opt.list]，你看看文档案例https://wocwin.github.io/t-ui-plus/components/TQueryCondition/base.html#%E7%BB%93%E5%90%88%E8%87%AA%E5%B7%B1%E5%B0%81%E8%A3%85%E7%BB%84%E4%BB%B6%E4%BD%BF%E7%94%A8

**Comment by zsasjy** [comment]
好的，可以的。还有个问题哈，期望schema中可以设置自身的labelWidth，还有schema可以提供一个显隐FormItem的条件。
