### ISSUE TITLE
TTable 组件 是否可以实现将 element ui 上 el-table 本身自带的一些 方法进行暴露出来呢

### ISSUE THREAD

**Issue by moneyliu0** [wocwin/t-ui-plus#22]
![image](https://github.com/wocwin/t-ui-plus/assets/101985663/46d268d7-2312-4fd6-9a7b-73841537afcd)
Table 方法 原表格上的一些方法,通过 ref 获取不到,是否可以暴露一下呢

**Comment by wocwin** [comment]
可以，下次发版生效

**Comment by wocwin** [comment]
1.2.5版本已发版
