### ISSUE TITLE
不支持TSX的组件

### ISSUE THREAD

**Issue by zhaoFangyi** [wocwin/t-ui-plus#3]
### 报错内容：
[plugin:vite:import-analysis] Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.
### 组件的内容
仅仅是一个简单的jsx组件
/packages/test-demo/src/test-demo.vue

```vue
<script lang="tsx">
export default {
  name: 'TestDemo',
  render() {
    const hasContent = false
    return <div>{hasContent || <el-input />}</div>
  },
}
</script>
```

**Comment by zhaoFangyi** [comment]
> ### 报错内容：
> [plugin:vite:import-analysis] Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.
> 
> ### 组件的内容
> 仅仅是一个简单的jsx组件 /packages/test-demo/src/test-demo.vue
> 
> ```
> <script lang="tsx">
> export default {
>   name: 'TestDemo',
>   render() {
>     const hasContent = false
>     return <div>{hasContent || <el-input />}</div>
>   },
> }
> </script>
> ```

**Comment by zhaoFangyi** [comment]
知道为什么了，加了一个vite.config.js

**Comment by JACK-ZHANG-coming** [comment]
vite.config.js是在哪里加的，加的什么内容？兄弟

**Comment by zhaoFangyi** [comment]
> vite.config.js是在哪里加的，加的什么内容？兄弟

docs/vite.config.ts 中加入@vitejs/plugin-vue-jsx的支持
