### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by canyuegongzi** [wocwin/t-ui-plus#30]
请问  1.1.12  之后版本是有破坏性的升级吗？我这边版本升级到 1.1.12的版本后项目报错
![image](https://github.com/wocwin/t-ui-plus/assets/32031360/314c6354-4e74-4e52-a60f-73c54f59c246)

**Comment by wocwin** [comment]
是不是因为升级了Vue及element-plus版本
![image](https://github.com/wocwin/t-ui-plus/assets/37534478/c7a1e165-91c9-4348-a5d2-ee5709d496f7)
