### ISSUE TITLE
请问如何全局size, elementui  的话可以通过use(ElementPlus, { size: 'small', zIndex: 3000 })

### ISSUE THREAD

**Issue by canyuegongzi** [wocwin/t-ui-plus#31]
请问如何全局size, elementui  的话可以通过use(ElementPlus, { size: 'small', zIndex: 3000 })， 但t-ui-plus底层应该是按需加载了 element, 我尝试instance.use(TuiPlus, { size: "large" })时无效

**Comment by wocwin** [comment]
直接设置element-plus就行了，像查询条件及表单组件的按钮size是特定设置的
