### ISSUE TITLE
1.2.13  版本 css 引入

### ISSUE THREAD

**Issue by propoet** [wocwin/t-ui-plus#35]
![image](https://github.com/wocwin/t-ui-plus/assets/19511924/283baac0-80ce-49b6-9377-9f99bfe11de8)
![image](https://github.com/wocwin/t-ui-plus/assets/19511924/f4d05f06-1493-43ea-a99f-67fdad2ed30f)
切换1.2.12 没发现问题

**Comment by wocwin** [comment]
1.2.13是测试版本，确实有问题，解决方案：你切换1.2.12或者安装最新版本
