### ISSUE TITLE
请教TAdaptivePage是否有slot添加额外的文字

### ISSUE THREAD

**Issue by alleluya-young** [wocwin/t-ui-plus#38]
![image](https://github.com/wocwin/t-ui-plus/assets/31433884/02fbd476-0243-4937-83e0-d4790f914515)
如图, 请教下像中间这行"请添加xxxx的信息"文字 现在的组件里能添加么? 我看文档里貌似是没有, 也不可能写在title里...

**Comment by wocwin** [comment]
title也可以是具名插槽，暂时可以用这种方式来写（需要写样式调整），后面我在加一个tip插槽
![image](https://github.com/wocwin/t-ui-plus/assets/37534478/ce35c408-c0cd-42b2-b577-3d1b27687005)

**Comment by wocwin** [comment]
最新版本1.3.0已加tipTitle，具体看TTable文档
