### ISSUE TITLE
使用语法糖报错，加载允许md文件失败，是怎么回事

### ISSUE THREAD

**Issue by miaoZai** [wocwin/t-ui-plus#4]
### 基础用法

:::demo `继承el-button所有属性` 

```vue
<template>
      <n-button type="tertiary">
      {{text}}
    </n-button>
</template>
<script lang="ts">
  export default {
    name: 'HomePage',
  };
</script>
<script setup lang="ts">
  import { ref } from 'vue';
  const text=ref('ab')
  
</script>

```

:::

**Comment by wocwin** [comment]
> ### 基础用法
> :::demo `继承el-button所有属性`
> 
> ```
> <template>
>       <n-button type="tertiary">
>       {{text}}
>     </n-button>
> </template>
> <script lang="ts">
>   export default {
>     name: 'HomePage',
>   };
> </script>
> <script setup lang="ts">
>   import { ref } from 'vue';
>   const text=ref('ab')
>   
> </script>
> ```
> 
> :::

应该是这个插件的原因vitepress-theme-demoblock

**Comment by wocwin** [comment]
> vitepress-theme-demoblock

目前已弃用vitepress-theme-demoblock插件，改用自己封装的demoblock组件
