### ISSUE TITLE
表格列筛选

### ISSUE THREAD

**Issue by WANGXIAOYU1995** [wocwin/t-ui-plus#43]
列筛选好像没实现，![image](https://github.com/user-attachments/assets/ffcdf253-8d56-4604-9849-bc13085bdfe1)

**Comment by wocwin** [comment]
组件已集成这个功能，element-plus怎么写，那么TTable就怎么写，我文档已添加示例，你可以参考来写。
![image](https://github.com/user-attachments/assets/2f00bc42-fcf1-4e8c-b7a2-62ca4568896a)
![image](https://github.com/user-attachments/assets/3e08f127-0bcf-48e2-a9bd-5c1a8867ff98)

**Comment by WANGXIAOYU1995** [comment]
收到
