### ISSUE TITLE
列的resizable没透传

### ISSUE THREAD

**Issue by tonylua** [wocwin/t-ui-plus#46]
rt 不起作用

**Comment by wocwin** [comment]
什么组件？什么问题？想要的效果是什么？

**Comment by tonylua** [comment]
背景：
column配置项中的resizable要搭配table上的border才能起效

问题：
1. 文档中对于border的使用是要在table配置项中，而不是prop形式
2. stripe、align 这类原本在el中和border平级的属性在ttable的prop中是起效的，造成调试时没有意识到

结果：
1. 改到table配置项中已调通
2. 是否可以考虑对齐这类属性的使用

**Comment by wocwin** [comment]
这个功能是element-plus官方自带的，开启边框就会自动开启resizable，后续我把border加在prop里面两种方式都支持，优先支持TTable标签方式
