### ISSUE TITLE
select-table 若干问题

### ISSUE THREAD

**Issue by staoran** [wocwin/t-ui-plus#48]
1. inputValue/modelValue/value 这几个属性绑定参数并选择后都没数据。
2. 单选模式，再次点击以选项的逻辑有问题，通过多次点击同一行可以发现，第一次：正常选择，第二次：算是取消选中吧（因为change事件得到的数据是空，但被选行还是高亮的），第三次：算是彻底取消选中了（change事件得到的数据是空，被选行的高亮没了），第四次：正常选择

**Comment by wocwin** [comment]
这个组件是通过事件获取选中的数据，v-model是无效的；inputValue只有设置isShowInput才生效。
第二点，麻烦录制一下视频

**Comment by staoran** [comment]
![recording](https://github.com/user-attachments/assets/d390926b-b626-416e-86e4-95e9d0183c5a)

**Comment by wocwin** [comment]
下次发版生效

**Comment by wocwin** [comment]
![fix selecttable](https://github.com/user-attachments/assets/daafb354-ce55-4c3d-9cd7-fc132d1283d0)

**Comment by wocwin** [comment]
![fix](https://github.com/user-attachments/assets/cfd9a955-02c6-4b14-ab3b-159f03b57507)

**Comment by staoran** [comment]
感谢
