### ISSUE TITLE
引入报错

### ISSUE THREAD

**Issue by liyangyang001** [wocwin/t-ui-plus#5]
Uncaught SyntaxError: The requested module '/node_modules/@wocwin/t-ui-plus/lib/t-ui-plus.umd.cjs?import' does not provide an export named 'default'

**Comment by wocwin** [comment]
> Uncaught SyntaxError: The requested module '/node_modules/@wocwin/t-ui-plus/lib/t-ui-plus.umd.cjs?import' does not provide an export named 'default'

安装最新版本
